export const COUNTRIES = [
  { value: 'KR', label: '대한민국' },
  { value: 'US', label: '미국' },
  { value: 'JP', label: '일본' },
  { value: 'CN', label: '중국' },
  { value: 'TW', label: '대만' },
  { value: 'HK', label: '홍콩' },
  { value: 'GB', label: '영국' },
  { value: 'DE', label: '독일' },
  { value: 'FR', label: '프랑스' },
  { value: 'IT', label: '이탈리아' },
  { value: 'ES', label: '스페인' },
  { value: 'NL', label: '네덜란드' },
  { value: 'CA', label: '캐나다' },
  { value: 'AU', label: '호주' },
  { value: 'NZ', label: '뉴질랜드' },
  { value: 'SG', label: '싱가포르' },
  { value: 'VN', label: '베트남' },
  { value: 'TH', label: '태국' },
  { value: 'PH', label: '필리핀' },
  { value: 'MY', label: '말레이시아' },
  { value: 'ID', label: '인도네시아' },
  { value: 'IN', label: '인도' },
  { value: 'BR', label: '브라질' },
  { value: 'MX', label: '멕시코' },
  { value: 'RU', label: '러시아' },
  { value: 'AE', label: '아랍에미리트' },
  { value: 'SA', label: '사우디아라비아' },
  { value: 'SE', label: '스웨덴' },
  { value: 'CH', label: '스위스' },
  { value: 'AT', label: '오스트리아' },
  { value: 'PL', label: '폴란드' },
  { value: 'TR', label: '튀르키예' },
  { value: 'ZA', label: '남아프리카공화국' },
] as const

export type CountryCode = (typeof COUNTRIES)[number]['value']
